= Appliance integration guide

== Prequisites

Chefy uses MQTT to connect user's smartphone with your appliance.
To integrate your device should support:

* MQTT
* TLS version 1.2
* X.509
* Time source (e.g. NTP, GPS)

== MQTT Topics and payloads

Cloud service expects your device to publish telemetry and faults and subscribe to configuration commands.
Message payloads are in JSON format as defined in the https://tools.ietf.org/html/rfc7159[RFC 7159].

[cols="1,1,1"]
|===

|Appliance telemetry
|`$devices/<device ID>/state`
|https://github.com/Chefy-cloud/spec-proposal/raw/main/telemetry-message.schema.json[Message Schema]

|Appliance faults
|`$devices/<device ID>/events`
|To be defined

|Appliance configuration commands
|`$devices/<device ID>/config`
|https://github.com/Chefy-cloud/spec-proposal/raw/main/control-message.schema.json[Message Schema]

|===

== Connection parameters

MQTT connection parameters:

* Broker host name: `mqtt.cloud.yandex.net`
* TCP port: 8883
* Security: TLSv1.2

== Authentication

MQTT connection is authenticated using X.509 certificates.
To authorize your device you should generate a certificate and make it available for Chefy cloud service.
The details of interaction with Chefy cloud service are to be defined.

== Device provisioning through mobile app

Provisioning is a process of onboarding your device to Wi-Fi network and associating your device with a Chefy user account.

The recomended modern way of Wi-Fi onboarding is https://www.wi-fi.org/download.php?file=/sites/default/files/private/Wi-Fi_Easy_Connect_Specification_v3.0.pdf[Wi-Fi Easy Connect].

For case where Wi-Fi Easy Connect is not supported, Chefy mobile app provides a mechanism for end users to supply Wi-Fi credentials to your device over Bluetooth Low Energy (BLE).
Mobile app uses Generic Attribute Profile to configure Wi-Fi credentials on your device.

Mobile app will not transmit Wi-Fi credentials over unencrypted channel.
To ensure security of Wi-Fi credentials transmission, your device should support Bluetooth Low Energy Security Mode 1, levels 2 through 4.
