= Appliance integration guide

== Prequisites

Chefy uses MQTT to connect user's smartphone with your appliance.
To integrate your device should support:

* MQTT
* TLS version 1.2
* X.509
* Time source (e.g. NTP, GPS)

== MQTT Topics and payloads

Cloud service expects your device to publish telemetry and faults and subscribe to configuration commands.
Message payloads are in JSON format as defined in the https://tools.ietf.org/html/rfc7159[RFC 7159].

[cols="1,1,1"]
|===

|Appliance telemetry
|`$devices/<device ID>/state`
|https://github.com/Chefy-cloud/spec-proposal/raw/main/telemetry-message.schema.json[Message Schema]

|Appliance faults
|`$devices/<device ID>/events`
|To be defined

|Appliance configuration commands
|`$devices/<device ID>/config`
|https://github.com/Chefy-cloud/spec-proposal/raw/main/control-message.schema.json[Message Schema]

|===

== Connection parameters

MQTT connection parameters:

* Broker host name: `mqtt.cloud.yandex.net`
* TCP port: 8883
* Security: TLSv1.2

== Authentication

MQTT connection is authenticated using X.509 certificates.
To authorize your device you should generate a certificate and make it available for Chefy cloud service.
The details of interaction with Chefy cloud service are to be defined.
